development:
  adapter: postgresql
  encoding: unicode
  database: scriptmanager_development
  host: localhost
  pool: 5
  username: kate
  password: <%= ENV["POSTGRES_SECRET"] %>

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: postgres
#   pool: 5
#   username: postgres
#   password: postgres
